  - name: Socket Security (Action)
  # You may pin to the exact commit or the version.
  # uses: SocketDev/action@8a97a84337775c5758dcf801bcbdc61963ad05d0
  uses: SocketDev/action@v1.1.2
  with:
    # Operation mode firewall or cli
    mode: 
    # GitHub API Token used for downloading binaries
    github-token: # default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # The Socket API Token
    socket-token: # optional
    # Cache the Socket binaries
    use-cache: # optional, default is true
    # Create a job summary
    job-summary: # optional, default is true
    # Specify the firewall version number
    firewall-version: # optional, default is latest
          
